version: "3"
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - ./:/home/jovyan/
    environment:
      - JUPYTER_ENABLE_LAB=1
    ports:
     - "8888:8888"
    restart: always
  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
     - "5432:5432"
volumes:
  pgdata: 